[package]
authors = ["Messense Lv <messense@icloud.com>"]
name = "word-count-cls"
version = "0.1.0"

[dependencies]
rayon = "0.8"

[dependencies.pyo3]
path = "../../"

[lib]
name = "word_count"
crate-type = ["cdylib"]
